#!/bin/sh

# first we set some variables
NAME=`whoami`
PROGRAM=/opt/md++1.41/bin/md
SIMULDIR=/home/jgarate/work/gromos/NPT.Lambda/10ALA/helix/md

# create temporary directory
WORKDIR=${SIMULDIR}
mkdir -p ${WORKDIR}
cd       ${WORKDIR}

# set the input files
TOPO=${SIMULDIR}/../../topo/10.ALA.ZeroC.top
IUNIT=${SIMULDIR}/md_peptide_5.imd
INPUTCRD=${SIMULDIR}/md_peptide_4.cnf
REFPOS=${SIMULDIR}/../box/10.ALA.BOX.rpr
POSRESSPEC=${SIMULDIR}/../box/10.ALA.BOX.por

#set the output files
OUNIT=md_peptide_5.omd
OUTPUTCRD=md_peptide_5.cnf
OUTPUTTRX=md_peptide_5.trc
OUTPUTTRE=md_peptide_5.tre


MDOK=1

${PROGRAM} \
	@topo        ${TOPO} \
	@conf        ${INPUTCRD} \
	@input       ${IUNIT} \
	@posresspec  ${POSRESSPEC} \
	@refpos      ${REFPOS} \
	@fin         ${OUTPUTCRD} \
	@trc         ${OUTPUTTRX} \
	@tre         ${OUTPUTTRE}\
	>            ${OUNIT}
grep "finished successfully" ${OUNIT} > /dev/null || MDOK=0

uname -a >> ${OUNIT}

# compress some files
gzip ${OUTPUTTRX}
gzip ${OUTPUTTRE}

# copy the files back
OK=1
cp ${OUNIT}               ${SIMULDIR} || OK=0
cp ${OUTPUTCRD}           ${SIMULDIR} || OK=0
cp ${OUTPUTTRX}.gz        ${SIMULDIR} || OK=0
cp ${OUTPUTTRE}.gz        ${SIMULDIR} || OK=0

# clean up after successful run
if `test ${OK} -eq 0`; then
  uname -a > mess;
  echo 'cp failed for md_peptide, run 5' >> mess;
  Mail -s "ERROR" ${NAME} < mess;
  cd ${SIMULDIR};
else
  cd ${SIMULDIR};
  rm ${WORKDIR}/*;
  rmdir ${WORKDIR};
fi

# stop if MD was not succesfull
if `test ${MDOK} -eq 0`; then
  exit
fi

# perform last command (usually submit next job)
cd ${SIMULDIR}
./md_peptide_6.run 
